#!/usr/bin/env bash
# Added A record name for load balancer and my web servers

subdomain_name () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
	subdomain_name "$2.$1" "$2"
else
	subdomain_name "www.$1" "www"
	subdomain_name "lb-01.$1" "lb-01"
	subdomain_name "web-01.$1" "web-01"
	subdomain_name "web-02.$1" "web-02"
fi
