#!/usr/bin/env bash
# Receiving an argument for an automatable task in bash script
#arg1 = $1
#arg2 = $2
#arg3 = $3
#arg4 = $4
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ];
then
	scp -i "$1" "$3"@"$2":~/
else
	scp -i "$4" "$1" "$3"@"$2":~/
fi
