#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages,
# let’s install one!

# Updating the server
apt-get -y update

# Installing Nginx
apt-get -y install nginx

# Installing a firewall and using it also
ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html

# Nginx testing server
nginx -t

# Starting Nginx server
service nginx start
