#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages,
# let’s install one!

# Updating the server
sudo apt-get update

# Installing Nginx
sudo apt-get install nginx

# Installing a firewall and using it also
sudo ufw 'Nginx HTTP'

echo "Hello world!" > /var/www/html/index.nginx-debian.html

# Testing The configuration of Nginx
sudo nginx -t

# Reloading Nginx after creating html
sudo service nginx reload
