#!/usr/bin/env bash
# Custom errorpage

# Updating package and installing nginx
sudo apt-get update
sudo apt-get install -y nginx

# An index.html page created
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirection being made with status code 301
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/gboigwe permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Created custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# HTTP response header served by hostname
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Configurations testing
sudo nginx -t

# Nginx restarting after implementing changes
sudo service nginx restart
