#!/usr/bin/env bash
# Configuring Nginx to listen on the port 80 of IPv4 IPs
sudo sed -i 's/listen\s\+[^;]\+;/listen 0.0.0.0:80;/g' /etc/nginx/nginx.conf
sudo service nginx restart
sudo pkill -o nginx
