#!/usr/bin/env bash
# This script displays a string after several integer
i=1
while [ "$i" -le 20 ]; do
	case "$i" in
		4|5)
			echo "bad luck from China"
			;;
		9|10)
			echo "bad luck from Japan"
			;;
		17|18)
			echo "bad luck from Japan"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
