#!/usr/bin/env bash
# Fixing Apache server to serve Hello Holberton page

# Start Apache server
sudo service apache2 start

# Create a temporary HTML file with "Hello Holberton" content
echo "Hello Holberton" > /etc/apache2.conf
#
# Replace default Apache index.html with the temporary file
#rm -f /var/www/html/index.html
#ln -s /tmp/hello.html /var/www/html/index.html
