#!/usr/bin/env bash
# Spcript that takes a new user as argument and print
# out the user whenever whoami is asked
if [ "$#" -eq 1 ];
then
	echo "Usage: ./0-iamsomeoneelse <username>"
	exit 1
fi
sudo -u "$1" whoami
