#!/usr/bin/env bash
# Configuring nginx to run as an nginx user and listen on 8080
sudo useradd -r nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
